apiVersion: v1
kind: Pod
metadata:
  name: hellocontainerpod
  labels:
    app: hellocontainer
spec:
  containers:
  - name: hellocontainer
    image: antsala/hello_container:latest
    ports:
    - containerPort: 8080

